let initialCharacter = [
    {
      name: "Schwarmeeze",
      key: 0,
      preset: "Preset",
      progress: {
        "Hilla": false,
        "PB": false,
        "Cygnus": false,
        "PNo": false,
        "Zakum": false,
        "Pierre": false,
        "Von Bon": false,
        "C Queen": false,
        "Vellum": false,
        "Magnus": false,
        "Papulatus": false,
        "Akechi": false,
        "Lotus": false,
        "Damien": false,
        "GA Slime": false,
        "Lucid": false,
        "Will": false,
        "Gloom": false,
        "V Hilla": false,
        "Darknell": false,
        "Seren": false,
        "Kalos": false,
        "Kaling": false,
      }
    },
    {
      name: "Schwarmeeze2",
      key: 1,
      preset: "Preset",
      progress: {
        "Hilla": false,
        "PB": false,
        "Cygnus": false,
        "PNo": false,
        "Zakum": false,
        "Pierre": false,
        "Von Bon": false,
        "C Queen": false,
        "Vellum": false,
        "Magnus": false,
        "Papulatus": false,
        "Akechi": false,
        "Lotus": false,
        "Damien": false,
        "GA Slime": false,
        "Lucid": false,
        "Will": false,
        "Gloom": false,
        "V Hilla": false,
        "Darknell": false,
        "Seren": false,
        "Kalos": false,
        "Kaling": false,
      }
    }]

  let initialPreset = [
    {
      name: "None",
      key: 0,
      content: {
        "Hilla": 0,
        "PB": 0,
        "Cygnus": 0,
        "PNo": 0,
        "Zakum": 0,
        "Pierre": 0,
        "Von Bon": 0,
        "C Queen": 0,
        "Vellum": 0,
        "Magnus": 0,
        "Papulatus": 0,
        "Akechi": 0,
        "Lotus": 0,
        "Damien": 0,
        "GA Slime": 0,
        "Lucid": 0,
        "Will": 0,
        "Gloom": 0,
        "V Hilla": 0,
        "Darknell": 0,
        "Seren": 0,
        "Kalos": 0,
        "Kaling": 0,
      }
    },
    {
      name: "Preset",
      key: 1,
      content: {
        "Hilla": 0,
        "PB": 0,
        "Cygnus": 0,
        "PNo": 0,
        "Zakum": 0,
        "Pierre": 3,
        "Von Bon": 3,
        "C Queen": 3,
        "Vellum": 3,
        "Magnus": 0,
        "Papulatus": 0,
        "Akechi": 0,
        "Lotus": 0,
        "Damien": 0,
        "GA Slime": 0,
        "Lucid": 0,
        "Will": 0,
        "Gloom": 0,
        "V Hilla": 0,
        "Darknell": 0,
        "Seren": 0,
        "Kalos": 0,
        "Kaling": 0,
      }
    },
    {
      name: "Preset1",
      key: 2,
      content: {
        "Hilla": 0,
        "PB": 0,
        "Cygnus": 0,
        "PNo": 0,
        "Zakum": 0,
        "Pierre": 0,
        "Von Bon": 0,
        "C Queen": 0,
        "Vellum": 0,
        "Magnus": 0,
        "Papulatus": 0,
        "Akechi": 0,
        "Lotus": 2,
        "Damien": 2,
        "GA Slime": 0,
        "Lucid": 0,
        "Will": 0,
        "Gloom": 0,
        "V Hilla": 0,
        "Darknell": 0,
        "Seren": 0,
        "Kalos": 0,
        "Kaling": 0,
      }
    }
  ]


const bossData = {
    "Hilla": {
        difficulties: ["None", null, null, "Hard", null],
        prices: [0, 0, 0, 56250000, 0]
    },
    //more bosses...
}

